language: node_js
node_js:
  - "node"
install:
  - git clone --branch=develop https://github.com/unitejs/framework.git unitejs/framework
  - cd unitejs/framework
  - npm link
  - cd ../../
  - npm link "unitejs-framework"
  - npm install gulp -g
script: 
  - gulp build || travis_terminate 1
  - gulp unit || travis_terminate 1
  - gulp coveralls || travis_terminate 1
  - cd assets/gulp || travis_terminate 1
  - npm install || travis_terminate 1
  - cd ../../ || travis_terminate 1
  - gulp build-gulp || travis_terminate 1
cache:
  directories:
  - node_modules
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18d04b26e3da5f9fa9dc
    on_success: change
    on_failure: always
    on_start: never