language: node_js
node_js:
  - "node"
install:
  - npm install
jobs:
  include:
  - stage: Build
  - stage: Unit Test
  - stage: Unit Test Results
  - script: gulp coveralls
cache:
  directories:
  - node_modules